apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deploy
  labels:
    name: postgres-deploy
    app: {{ .Values.app }}
spec:
  replicas: 1
  selector:
    matchLabels:
      name: postgres-pod
      app: {{ .Values.app }}
  template:
    metadata:
      name: postgres-pod
      labels:
        name: postgres-pod
        app: {{ .Values.app }}
    spec:
      containers:
      - name: {{ .Values.images.postgres.name }}
        image: {{ .Values.images.postgres.image }}
        ports:
        - containerPort: 5432
        env:
          - name: POSTGRES_USER
            value: "postgres"
          - name: POSTGRES_PASSWORD
            value: "postgres"
          - name: POSTGRES_HOST_AUTH_METHOD
            value: trust