---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: result-app-deploy
  labels:
    name: result-app-deploy
    app: {{ .Values.app }}
spec:
  replicas: 1
  selector:
    matchLabels:
      name: result-app-pod
      app: {{ .Values.app }}
  template:
    metadata:
      name: result-app-pod
      labels:
        name: result-app-pod
        app: {{ .Values.app }}
    spec:
      containers:
      - name: {{ .Values.images.resultApp.name }}
        image: {{ .Values.images.resultApp.image }}
        ports:
        - containerPort: {{ .Values.service.ports.resultApp.port }}