---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.ports.resultApp.name }}
  labels:
    name: {{ .Values.service.ports.resultApp.name }}
    app: {{ .Values.app }}
spec:
  type: NodePort
  ports:
  - port: {{ .Values.service.ports.resultApp.port }}
    targetPort: {{ .Values.service.ports.resultApp.targetport }}
    nodePort: {{ .Values.service.ports.resultApp.nodePort }}
  selector:
    name: result-app-pod
    app: {{ .Values.app }}
