---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.ports.votingApp.name }}
  labels:
    name: {{ .Values.service.ports.votingApp.name }}
    app: {{ .Values.app }}
spec:
  type: NodePort
  ports:
  - port: {{ .Values.service.ports.votingApp.port }}
    targetPort: {{ .Values.service.ports.votingApp.targetport }}
    nodePort: {{ .Values.service.ports.votingApp.nodePort }}
  selector:
    name: voting-app-pod
    app: {{ .Values.app }}
